import{schedule,workouts}from'./data.js';import*as cloud from'./firebase-sync.js';
const KEY='ironhybrid.logs.v1',state={date:localDate(),logs:JSON.parse(localStorage.getItem(KEY)||'{}'),view:'todayView',user:null,configured:false,deferred:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function localDate(d=new Date()){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}
function parseDate(s){return new Date(s+'T12:00:00')}function dayName(d){return['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'][d.getDay()]}
function logId(date,wid){return`${date}_${wid}`}function getLog(date,wid){const id=logId(date,wid);return state.logs[id]||{id,date,workoutId:wid,sets:{},notes:{},readiness:'normal',finished:false,updatedAt:null}}
function persist(log){log.updatedAt=new Date().toISOString();state.logs[log.id]=log;localStorage.setItem(KEY,JSON.stringify(state.logs));if(state.user)cloud.saveRemote(log.id,log).then(()=>setSync(true)).catch(()=>setSync(false));renderProgressOnly()}
function setSync(ok){const el=$('#syncStatus');el.classList.toggle('online',ok);el.innerHTML=`<span></span>${ok?'Sincronizado':state.configured?'Offline':'Local'}`}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function exerciseSets(ex){const m=ex.scheme.match(/^(\d+)(?:–(\d+))?/);return Number(m?.[2]||m?.[1]||3)}
function renderToday(){const d=parseDate(state.date),cfg=schedule[d.getDay()]||{},wid=cfg.workout;$('#todayLabel').textContent=`${dayName(d).toUpperCase()} • ${d.toLocaleDateString('pt-BR')}`;const ready=$('#readinessCard');ready.innerHTML=`<div class="readiness-head"><b>Como você está hoje?</b><small>ajusta sua decisão</small></div><div class="readiness-options">${['ótimo','normal','cansado'].map(x=>`<button data-ready="${x}">${x}</button>`).join('')}</div>`;if(!wid){$('#todayContent').innerHTML=`<div class="rest-day"><b>${cfg.run||'Recuperação'}</b><h2>Sem musculação programada</h2><p>Use o dia para executar a corrida prevista e preservar a recuperação.</p></div>`;$$('[data-ready]').forEach(b=>b.onclick=()=>b.classList.toggle('active'));return}const w=workouts[wid],log=getLog(state.date,wid);$$('[data-ready]').forEach(b=>{b.classList.toggle('active',b.dataset.ready===log.readiness);b.onclick=()=>{log.readiness=b.dataset.ready;persist(log);renderToday()}});$('#todayContent').innerHTML=sessionHTML(w,log,cfg.run);bindSession(w,log)}
function sessionHTML(w,log,run){const total=w.exercises.reduce((n,e)=>n+exerciseSets(e),0),done=Object.values(log.sets).filter(set=>set?.done).length,pct=Math.round(done/total*100)||0;return`<article class="session-hero"><span class="tag">${w.day.toUpperCase()}</span><h2>${w.name}</h2><p>${w.subtitle}</p><div class="session-meta">${run?`<span class="chip">🏃 ${run}</span>`:''}<span class="chip">⏱ ${w.duration}</span><span class="chip">${w.focus}</span></div><div class="progress-track"><span style="width:${pct}%"></span></div><small>${done} de ${total} séries concluídas</small></article>${w.exercises.map((e,i)=>exerciseHTML(e,i,log)).join('')}<button id="finishWorkout" class="finish-btn">${log.finished?'Treino concluído ✓':'Concluir treino'}</button>`}
function exerciseHTML(e,i,log){const count=exerciseSets(e),all=[...Array(count)].every((_,s)=>log.sets[`${i}-${s}`]?.done);const technique=e.execution?`<div class="technique hidden"><h4>Preparação</h4><ol>${(e.setup||[]).map(x=>`<li>${x}</li>`).join('')}</ol><h4>Execução</h4><ol>${e.execution.map(x=>`<li>${x}</li>`).join('')}</ol><h4>Evite</h4><ul>${(e.errors||[]).map(x=>`<li>${x}</li>`).join('')}</ul></div>`:'';return`<article class="exercise-card ${all?'completed':''}" data-ex="${i}"><div class="exercise-head"><span class="exercise-index">${i+1}</span><div class="exercise-title"><h3>${e.name}</h3><p>${e.scheme} • ${e.rir||''} • ${e.rest||''}${e.method?` • ${e.method}`:''}</p></div>${technique?'<button class="exercise-toggle" aria-label="Ver execução">⌄</button>':''}</div><div class="sets">${[...Array(count)].map((_,s)=>{const k=`${i}-${s}`,v=log.sets[k]||{};return`<div class="set-row"><span class="set-label">S${s+1}</span><input inputmode="decimal" data-field="load" data-key="${k}" placeholder="kg" value="${v.load||''}"><input inputmode="numeric" data-field="reps" data-key="${k}" placeholder="reps" value="${v.reps||''}"><button class="check-set ${v.done?'done':''}" data-check="${k}">✓</button></div>`}).join('')}<textarea class="exercise-notes" data-note="${i}" placeholder="Observação do exercício">${log.notes[i]||''}</textarea></div>${technique}</article>`}
function bindSession(w,log){$$('.exercise-toggle').forEach(b=>b.onclick=()=>{b.closest('.exercise-card').querySelector('.technique').classList.toggle('hidden');b.textContent=b.textContent==='⌄'?'⌃':'⌄'});$$('.set-row input').forEach(x=>x.onchange=()=>{const k=x.dataset.key;log.sets[k]=typeof log.sets[k]==='object'?log.sets[k]:{};log.sets[k][x.dataset.field]=x.value;persist(log)});$$('[data-check]').forEach(b=>b.onclick=()=>{const k=b.dataset.check;log.sets[k]=typeof log.sets[k]==='object'?log.sets[k]:{};log.sets[k].done=!log.sets[k].done;persist(log);renderToday()});$$('[data-note]').forEach(x=>x.onchange=()=>{log.notes[x.dataset.note]=x.value;persist(log)});$('#finishWorkout').onclick=()=>{log.finished=!log.finished;persist(log);toast(log.finished?'Treino concluído':'Treino reaberto');renderToday()}}
function renderWeek(){const base=parseDate(state.date),today=base.getDay();$('#weekGrid').innerHTML=[1,2,3,4,5,6,0].map(day=>{const c=schedule[day],w=c.workout&&workouts[c.workout];return`<button class="day-card ${day===today?'current':''}" data-day="${day}"><span class="day-name">${['DOMINGO','SEGUNDA','TERÇA','QUARTA','QUINTA','SEXTA','SÁBADO'][day]}</span><h2>${w?w.name:c.run||'Recuperação'}</h2><p>${[c.run,w?.subtitle].filter(Boolean).join(' • ')}</p></button>`}).join('');$$('[data-day]').forEach(b=>b.onclick=()=>{const target=Number(b.dataset.day),d=parseDate(state.date),diff=(target-d.getDay()+7)%7;d.setDate(d.getDate()+diff);state.date=localDate(d);switchView('todayView')})}
function renderHistory(){const logs=Object.values(state.logs).sort((a,b)=>b.date.localeCompare(a.date));const finished=logs.filter(x=>x.finished);$('#historySummary').innerHTML=`<div class="stat"><b>${finished.length}</b><small>concluídos</small></div><div class="stat"><b>${logs.length}</b><small>registros</small></div><div class="stat"><b>${new Set(finished.map(x=>x.date.slice(0,7))).size}</b><small>meses ativos</small></div>`;$('#historyFilter').innerHTML='<option value="all">Todos os treinos</option>'+Object.entries(workouts).filter(([k])=>k!=='core-sunday').map(([k,w])=>`<option value="${k}">${w.name}</option>`).join('');const draw=()=>{const f=$('#historyFilter').value;const arr=logs.filter(x=>f==='all'||x.workoutId===f);$('#historyList').innerHTML=arr.length?arr.map(x=>`<article class="history-item"><header><b>${workouts[x.workoutId]?.name||x.workoutId}</b><span>${parseDate(x.date).toLocaleDateString('pt-BR')}</span></header><p>${Object.values(x.sets).filter(s=>s.done).length} séries marcadas • ${x.finished?'Concluído':'Em andamento'}</p></article>`).join(''):'<div class="rest-day">Nenhum treino registrado.</div>'};$('#historyFilter').onchange=draw;draw()}
function renderProgressOnly(){if(state.view==='historyView')renderHistory()}
function switchView(id){state.view=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='todayView')renderToday();if(id==='weekView')renderWeek();if(id==='historyView')renderHistory();scrollTo(0,0)}
function exportData(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),logs:state.logs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ironhybrid-backup-${localDate()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function setupCloud(){try{const r=await cloud.initFirebase(u=>{state.user=u;$('#authLoggedOut').classList.toggle('hidden',!!u);$('#authLoggedIn').classList.toggle('hidden',!u);$('#userEmail').textContent=u?.email||'';if(u){setSync(true);cloud.watchRemote(items=>{for(const x of items){if(!state.logs[x.id]||x.updatedAt>state.logs[x.id].updatedAt)state.logs[x.id]=x}localStorage.setItem(KEY,JSON.stringify(state.logs));renderToday()})}else setSync(false)});state.configured=r.configured;if(!r.configured)$('#firebaseHelp').textContent='Modo local ativo. Preencha firebase-config.js para habilitar login e sincronização.'}catch(e){setSync(false);$('#firebaseHelp').textContent='Não foi possível iniciar o Firebase. O modo local continua funcionando.'}}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#calendarBtn').onclick=()=>$('#datePicker').showPicker();$('#datePicker').value=state.date;$('#datePicker').onchange=e=>{state.date=e.target.value;renderToday()};$('#exportBtn').onclick=exportData;$('#importInput').onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text());state.logs=j.logs||j;localStorage.setItem(KEY,JSON.stringify(state.logs));toast('Dados importados');renderToday()}catch{toast('Arquivo inválido')}};$('#resetBtn').onclick=()=>$('#confirmDialog').showModal();$('#confirmDialog').addEventListener('close',()=>{if($('#confirmDialog').returnValue==='confirm'){state.logs={};localStorage.removeItem(KEY);renderToday();toast('Check-ins removidos')}});$('#loginBtn').onclick=async()=>{try{await cloud.signIn($('#emailInput').value,$('#passwordInput').value);toast('Conectado')}catch(e){toast('Falha ao entrar')}};$('#signupBtn').onclick=async()=>{try{await cloud.signUp($('#emailInput').value,$('#passwordInput').value);toast('Conta criada')}catch(e){toast('Falha ao criar conta')}};$('#logoutBtn').onclick=()=>cloud.signOutUser();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferred=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{await state.deferred?.prompt();state.deferred=null;$('#installBtn').classList.add('hidden')};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));renderToday();setupCloud();
